name: ChatLogger
main: kenygamer\ChatLogger\Main
version: 1.2
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/ChatLogger

permissions:
 chatlogger.bypass:
  default: false
