name: CapsLimiter
main: kenygamer\CapsLimiter\Main
version: 1.0.2
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/CapsLimiter

commands:
 limit:
  permission: capslimiter.command
