name: CapsLimiter
main: kenygamer\CapsLimiter\Main
version: 1.2
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/CapsLimiter

commands:
 limit:
  permission: capslimiter.command

permissions:
 capslimiter.command:
  description: Allows you to use /limit
  default: op
 capslimiter.bypass:
  description: Allows you to bypass capital letters
  default: false
