name: CapsLimiter
main: kenygamer\CapsLimiter\Main
version: 1.2
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/CapsLimiter

commands:
 limit:
  description: Sets the capital letters limit.
  permission: capslimiter.command
  usage: /limit <value>

permissions:
 capslimiter.command:
  default: op
 capslimiter.bypass:
  default: false
