name: Coords
main: kenygamer\Coords\Main
version: 3.1
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/Coords

commands:
 coords:
  default: true
 coordtags:
  default: op
 coordupdate:
  default: op
  
permissions:
 coords.command.coords:
  default: true
 coords.command.see:
  default: op
 coords.command.tags:
  default: op
 coords.command.update:
  default: op
