name: Coords
main: kenygamer\Coords\Main
version: 3.1
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/Coords

commands:
 coords:
  default: true
  description: "Prints out your or other players' coordinates."
  usage: /coords [player]
 coordtags:
  default: op
  description: Lists available tags for formatting the /coords message.
  usage: /coordtags
 coordupdate:
  default: op
  description: Sets the /coords message.
  usage: /coordupdate <message>
  
permissions:
 coords.command.coords:
  default: true
 coords.command.see:
  default: op
 coords.command.tags:
  default: op
 coords.command.update:
  default: op
