name: HideMe
main: kenygamer\HideMe\Main
version: 1.2
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/HideMe

commands:
 hide:
  permission: hideme.commands
 unhide:
  permission: hideme.commands
  
permissions:
 hideme.commands:
  default: op
