name: HideMe
main: kenygamer\HideMe\Main
version: 1.2
api:
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/HideMe

commands:
 hide:
  description: Hides or modifies your nametag temporalily.
  permission: hideme.commands
  usage: /hide [nametag]
 unhide:
  description: Unhides/fixes your nametag.
  permission: hideme.commands
  usage: /unhide
  
permissions:
 hideme.commands:
  default: op
