name: KillMoney
main: kenygamer\KillMoney\Main
version: 1.1.3
api: 3.0.0-ALPHA7

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/KillMoney

commands:
 killmoney:
  usage: "/killmoney"
  default: true
  
permissions:
 killmoney.command:
  default: op
 killmoney.killer.receive.money:
  default: true
 killmoney.victim.lose.money:
  default: false
